var $ = '$';
module.exports = [
  ["Albanian Lek", "ALL", "L"],
  ["Algerian Dinar", "DZD", "د.ج"],
  ["Argentine Peso", "ARS", $],
  ["Aruba Florin", "AWG", "ƒ"],
  ["Australian Dollar", "AUD", $, "AUD"],
  ["Bahamian Dollar", "BSD", $],
  ["Bahraini Dinar", "BHD", ".د.ب"],
  ["Bangladesh Taka", "BDT", "৳"],
  ["Barbados Dollar", "BBD", $],
  ["Belarus Ruble", "BYR", "Br"],
  ["Belize Dollar", "BZD", $],
  ["Bermuda Dollar", "BMD", $],
  ["Bhutan Ngultrum", "BTN", "Nu"],
  ["Bolivian Boliviano", "BOB", "Bs"],
  ["Botswana Pula", "BWP", "P"],
  ["Brazilian Real", "BRL", "R$"],
  ["British Pound", "GBP", "£"],
  ["Brunei Dollar", "BND", $],
  ["Bulgarian Lev", "BGN", "лв"],
  ["Burundi Franc", "BIF", "Fr"],
  ["Cambodia Riel", "KHR", "៛"],
  ["Canadian Dollar", "CAD", $],
  ["Cape Verde Escudo", "CVE", $],
  ["Cayman Islands Dollar", "KYD", $],
  ["Chilean Peso", "CLP", $],
  ["Chinese Yuan", "CNY", "¥"],
  ["Colombian Peso", "COP", $],
  ["Comoros Franc", "KMF", "Fr"],
  ["Costa Rica Colon", "CRC", "₡"],
  ["Croatian Kuna", "HRK", "kn"],
  ["Cuban Peso", "CUP", $],
  ["Czech Koruna", "CZK", "Kč"],
  ["Danish Krone", "DKK", "kr", "DKK"],
  ["Dijibouti Franc", "DJF", "Fr"],
  ["Dominican Peso", "DOP", $],
  ["East Caribbean Dollar", "XCD", $, "XCD"],
  ["Egyptian Pound", "EGP", "ج.م"],
  ["El Salvador Colon", "SVC", "₡"],
  ["Eritrea Nakfa", "ERN", "Nfk"],
  ["Ethiopian Birr", "ETB", "Br"],
  ["Euro", "EUR", "€", "EUR"],
  ["Falkland Islands Pound", "FKP", "£"],
  ["Fiji Dollar", "FJD", $],
  ["Gambian Dalasi", "GMD", "D"],
  ["Guatemala Quetzal", "GTQ", "Q"],
  ["Guinea Franc", "GNF", "Fr"],
  ["Guyana Dollar", "GYD", $],
  ["Haiti Gourde", "HTG", "G"],
  ["Honduras Lempira", "HNL", "L"],
  ["Hong Kong Dollar", "HKD", $],
  ["Hungarian Forint", "HUF", "Ft"],
  ["Iceland Krona", "ISK", "kr"],
  ["Indian Rupee", "INR", ""],
  ["Indonesian Rupiah", "IDR", "Rp"],
  ["Iran Rial", "IRR", "﷼"],
  ["Iraqi Dinar", "IQD", "ع.د"],
  ["Israeli Shekel", "ILS", "₪"],
  ["Jamaican Dollar", "JMD", $],
  ["Japanese Yen", "JPY", "¥"],
  ["Jordanian Dinar", "JOD", "د.ا"],
  ["Kazakhstan Tenge", "KZT", "₸"],
  ["Kenyan Shilling", "KES", "Sh"],
  ["Kuwaiti Dinar", "KWD", "د.ك"],
  ["Lao Kip", "LAK", "₭"],
  ["Latvian Lat", "LVL", "Ls"],
  ["Lebanese Pound", "LBP", "ل.ل"],
  ["Lesotho Loti", "LSL", "L"],
  ["Liberian Dollar", "LRD", $],
  ["Libyan Dinar", "LYD", "ل.د"],
  ["Lithuanian Lita", "LTL", "Lt"],
  ["Macau Pataca", "MOP", "P"],
  ["Macedonian Denar", "MKD", "ден"],
  ["Malawi Kwacha", "MWK", "MK"],
  ["Malaysian Ringgit", "MYR", "MR"],
  ["Maldives Rufiyaa", "MVR", ".ރ"],
  ["Mauritania Ougulya", "MRO", "UM"],
  ["Mauritius Rupee", "MUR", "Rs"],
  ["Mexican Peso", "MXN", $],
  ["Moldovan Leu", "MDL", "L"],
  ["Mongolian Tugrik", "MNT", "₮"],
  ["Moroccan Dirham", "MAD", "د.م."],
  ["Myanmar Kyat", "MMK", "Ks"],
  ["Namibian Dollar", "NAD", $],
  ["Nepalese Rupee", "NPR", "Rs"],
  ["New Zealand Dollar", "NZD", $],
  ["Nicaragua Cordoba", "NIO", "C$"],
  ["Nigerian Naira", "NGN", "₦"],
  ["North Korean Won", "KPW", "₩"],
  ["Norwegian Krone", "NOK", "kr"],
  ["Omani Rial", "OMR", "ر.ع."],
  ["Pacific Franc", "XPF", "Fr", "XPF"],
  ["Pakistani Rupee", "PKR", "Rs"],
  ["Panama Balboa", "PAB", "B/."],
  ["Papua New Guinea Kina", "PGK", "K"],
  ["Paraguayan Guarani", "PYG", "₲"],
  ["Peruvian Nuevo Sol", "PEN", "S/."],
  ["Philippine Peso", "PHP", "₱"],
  ["Polish Zloty", "PLN", "zł"],
  ["Qatar Rial", "QAR", "ر.ق"],
  ["Romanian New Leu", "RON", "L"],
  ["Russian Rouble", "RUB", "руб."],
  ["Rwanda Franc", "RWF", "Fr"],
  ["Samoa Tala", "WST", "T"],
  ["Sao Tome Dobra", "STD", "Db"],
  ["Saudi Arabian Riyal", "SAR", "ر.س"],
  ["Seychelles Rupee", "SCR", "Rs"],
  ["Sierra Leone Leone", "SLL", "Le"],
  ["Singapore Dollar", "SGD", $],
  ["Solomon Islands Dollar", "SBD", $],
  ["Somali Shilling", "SOS", "Sh"],
  ["South African Rand", "ZAR", "R", "ZAR"],
  ["South Korean Won", "KRW", "₩"],
  ["Sri Lanka Rupee", "LKR", "Rs"],
  ["St Helena Pound", "SHP", "£"],
  ["Sudanese Pound", "SDG", $],
  ["Swaziland Lilageni", "SZL", "L"],
  ["Swedish Krona", "SEK", "kr"],
  ["Swiss Franc", "CHF", "Fr", "CHF"],
  ["Syrian Pound", "SYP", "£"],
  ["Taiwan Dollar", "TWD", $],
  ["Tanzanian Shilling", "TZS", "Sh"],
  ["Thai Baht", "THB", "฿"],
  ["Tonga Pa'ang", "TOP", "T$"],
  ["Trinidad & Tobago Dollar", "TTD", $],
  ["Tunisian Dinar", "TND", "د.ت"],
  ["Turkish Lira", "TRY", "&#8378;"],
  ["UAE Dirham", "AED", "د.إ"],
  ["Ugandan Shilling", "UGX", "Sh"],
  ["Ukraine Hryvnia", "UAH", "₴"],
  ["United States Dollar", "USD", $],
  ["Uruguayan New Peso", "UYU", $],
  ["Vanuatu Vatu", "VUV", "Vt"],
  ["Venezuelan Bolivar Fuerte", "VEF", "Bs F"],
  ["Vietnam Dong", "VND", "₫"],
  ["Yemen Riyal", "YER", "﷼"]
].map(function (a) {
  return {
    name:   a[0],
    code:   a[1],
    symbol: a[2],
    flag:   'flag-' + (a[3] || a[1].substr(0, 2))
  };
});
